### ISSUE TITLE
Interested To Learn More

### ISSUE THREAD

**Issue by PrometheusR** [dc-ying/My_QA#1]
The QA project you have done was an impressive work, and I really want to learn more from your code. I am aware that there is another project in EE448, which is about node-classification. Could you please upload that part too so that I can star it and learn how to do the project? Thank you very much!

Best regards!

**Comment by dc-ying** [comment]
Thanks for your compliment 😄 I'm quite busy focusing on the [iFood-challenge](https://github.com/dc-ying/Our-iFood-2019) and an NB-Iot contest recently, and I'll upload the node-classification project later when I have a clear idea. Maybe we can improve them together. If you are an EE student, I think you can contact me via WeChat or QQ.
